# Built in R version 3.4.4

#source('global.R')

shinyUI(fluidPage(theme = "yeti_custom.css", 
                  navbarPage('VDEQ Statewide Attribution Workshop',
                             tabPanel('About',fluidRow(column(10,
                                                              h5("This data visualization tool was created to assist VDEQ staff, TetraTech, and 
                                                                 expert panelists throughout the Virginia fish and macroinvertebrate attribution process."),
                                                              p("Data included in analyses include fish, macroinvertebrate, and water chemistry data collected at
                                                                wadeable sites throughout Virginia and West Virginia. Data was contributed by the VDEQ 
                                                                Probabilistic Monitoring Program, West Virginia DEP, Maryland DNR, Fairfax County, and EPA's national 
                                                                assessments including NRSA, MAHA, and MAIA."), 
                                                              p("This visualization tool organizes statistical analyses of species 
                                                                occurrence across stressor gradients. Cumulative distribution functions (CDF), General Additive
                                                                Models (GAM), and Threshold Indicator Taxa Analysis (TITAN) models are presented alongside 
                                                                species distribution maps to assist panelists in the BCG attribution decision process."),
                                                              br(),
                                                              p('Please contact Emma Jones for troubleshooting issues: emma.jones@deq.virginia.gov')))),
                             tabPanel('Fish',
                                                 div('data-spy'="affix", 'data-offset-top'="100",
                                                     #wellPanel(
                                                     fluidRow(column(2),
                                                              column(10,selectInput('fishSpecies',strong('Species'),choices = names(stationBySpeciesUniqueList),width = '50%')))),
                                                 h4('Species Distribution Map'),
                                                 leafletOutput('FISH_distMap', height=400),
                                                 br(),br(),br(),br(),hr(),
                                                 tabsetPanel(
                                                   tabPanel('Dissolved Oxygen',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('DO')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('DOsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('DOsubpop'))),br()),
                                                   tabPanel('pH',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('pH')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('pHsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('pHsubpop'))),br()),
                                                   tabPanel('Specific Conductivity',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('SpCond')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('SpCondsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('SpCondsubpop'))),br()),
                                                   tabPanel('Total Phosphorus',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('TP')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('TPsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('TPsubpop'))),br()),
                                                   tabPanel('Total Nitrogen',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('TN')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('TNsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('TNsubpop'))),br()),
                                                   tabPanel('Total Habitat',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('TotHab')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('TotHabsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('TotHabsubpop'))),br()),
                                                   tabPanel('Total Habitat (with MD)',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('TotHab_wMD')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('TotHab_wMDsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('TotHab_wMDsubpop'))),br()),
                                                   tabPanel('LRBS',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('LRBS')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('LRBSsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('LRBSsubpop'))),br()),
                                                   tabPanel('Percent Impervious',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('wshdImpPCT')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('wshdImpPCTsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('wshdImpPCTsubpop'))),br()),
                                                   tabPanel('Sulfate',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('Sf')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('SfsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('Sfsubpop'))),br()),
                                                   tabPanel('Chloride',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('Cl')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('ClsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('Clsubpop'))),br())
                                                 
                                                 
                                        )#,
                                        
                                        #tabPanel('Titan Overview',
                                        #         helpText("This tab allows users to view the Titan model to help determine
                                        #                  overall picture of 'gainers' vs 'losers' by stressor. Use the drop
                                        #                  down menu to update the model by stressor."),
                                        #         selectInput('fishTitanOverview','Choose a parameter',
                                        #                     choices = c('Dissolved Oxygen','pH','Specific Conductivity',
                                        #                                 'Total Phosphorus', 'Total Nitrogen', 
                                        #                                 'Total Habitat','LRBS','Percent Impervious')),
                                        #         titanOverviewPlottingUI('fishTitanOverviewPlot'))
                                        ),
                             navbarMenu('Macroinvertebrates',
                                        tabPanel('Spring Macroinvertebrates',
                                                 div('data-spy'="affix", 'data-offset-top'="100",
                                                     #wellPanel(
                                                     fluidRow(column(2),
                                                              column(10,selectInput('bugSpecies',strong('Species'),choices = names(bugstationBySpeciesUniqueList), width = '50%')))),
                                                 h4('Species Distribution Map'),
                                                 leafletOutput('BUG_distMap', height=400),
                                                 br(),br(),br(),br(),hr(),
                                                 tabsetPanel(
                                                   tabPanel('Dissolved Oxygen',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('bugDO')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('bugDOsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('bugDOsubpop')))),
                                                   tabPanel('pH',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('bugpH')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('bugpHsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('bugpHsubpop')))),
                                                   tabPanel('Specific Conductivity',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('bugSpCond')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('bugSpCondsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('bugSpCondsubpop')))),
                                                   tabPanel('Total Phosphorus',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('bugTP')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('bugTPsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('bugTPsubpop')))),
                                                   tabPanel('Total Nitrogen',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('bugTN')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('bugTNsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('bugTNsubpop')))),
                                                   tabPanel('Total Habitat',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('bugTotHab')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('bugTotHabsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('bugTotHabsubpop')))),
                                                   tabPanel('Total Habitat (with MD)',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('bugTotHab_wMD')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('bugTotHab_wMDsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('bugTotHab_wMDsubpop')))),
                                                   tabPanel('LRBS',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('bugLRBS')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('bugLRBSsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('bugLRBSsubpop')))),
                                                   tabPanel('Percent Impervious',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('bugwshdImpPCT')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('bugwshdImpPCTsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('bugwshdImpPCTsubpop')))),
                                                   tabPanel('Sulfate',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('bugSf')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('bugSfsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('bugSfsubpop')))),
                                                   tabPanel('Chloride',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('bugCl')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('bugClsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('bugClsubpop'))))
                                                   
                                                 )),
                                        #tabPanel('Spring Titan Overview',
                                        #         helpText("This tab allows users to view the Titan model to help determine
                                        #                  overall picture of 'gainers' vs 'losers' by stressor. Use the drop
                                        #                  down menu to update the model by stressor."),
                                        #         selectInput('bugTitanOverview','Choose a parameter',
                                        #                     choices = c('Dissolved Oxygen','pH','Specific Conductivity',
                                        #                                 'Total Phosphorus', 'Total Nitrogen', 
                                        #                                 'Total Habitat','LRBS','Percent Impervious')),
                                        #         titanOverviewPlottingUI('bugTitanOverviewPlot')),
                                        
                                        tabPanel('Fall Macroinvertebrates',
                                                 div('data-spy'="affix", 'data-offset-top'="100",
                                                     #wellPanel(
                                                     fluidRow(column(2),
                                                              column(10,selectInput('fallbugSpecies',strong('Species'),choices = c("",names(fallbugstationBySpeciesUniqueList)), width = '50%')))),
                                                 h4('Species Distribution Map'),
                                                 leafletOutput('FALLBUG_distMap', height=400),
                                                 br(),br(),br(),br(),hr(),
                                                 tabsetPanel(
                                                   tabPanel('Dissolved Oxygen',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('fallbugDO')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('fallbugDOsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('fallbugDOsubpop')))),
                                                   tabPanel('pH',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('fallbugpH')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('fallbugpHsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('fallbugpHsubpop')))),
                                                   tabPanel('Specific Conductivity',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('fallbugSpCond')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('fallbugSpCondsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('fallbugSpCondsubpop')))),
                                                   tabPanel('Total Phosphorus',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('fallbugTP')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('fallbugTPsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('fallbugTPsubpop')))),
                                                   tabPanel('Total Nitrogen',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('fallbugTN')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('fallbugTNsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('fallbugTNsubpop')))),
                                                   tabPanel('Total Habitat',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('fallbugTotHab')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('fallbugTotHabsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('fallbugTotHabsubpop')))),
                                                   tabPanel('Total Habitat (with MD)',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('fallbugTotHab_wMD')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('fallbugTotHab_wMDsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('fallbugTotHab_wMDsubpop')))),
                                                   tabPanel('LRBS',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('fallbugLRBS')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('fallbugLRBSsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('fallbugLRBSsubpop')))),
                                                   tabPanel('Percent Impervious',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('fallbugwshdImpPCT')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('fallbugwshdImpPCTsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('fallbugwshdImpPCTsubpop')))),
                                                   tabPanel('Sf',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('fallbugSf')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('fallbugSfsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('fallbugSfsubpop')))),
                                                   tabPanel('Cl',
                                                            fluidRow(column(6,
                                                                            fluidRow(column(4),column(8,h1('Statewide'))),br(),br(),br(),
                                                                            plotsOnTabUI('fallbugCl')),
                                                                     column(6,
                                                                            fluidRow(column(3),
                                                                                     column(9,selectInput('fallbugClsubpopInput',strong('Bioregion'),
                                                                                                          choices = c('Mountain','Piedmont','Coast')))),br(),br(),br(),
                                                                            plotsOnTabSubpopUI('fallbugClsubpop'))))
                                                 ))
                                        ))))

